version: "3"

services:
  db_postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  biblioteca_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - biblioteca_app
  
  # supervisor:
  #   build:
  #     context: .
  #   volumes:
  #     - ./supervisor/conf.d/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
  #     - ./biblioteca:/app
  #   command: supervisord -n
  #   depends_on:
  #     - biblioteca_app
volumes:
  .:
  postgres_data:
  static:
